[[mgr.prepend_keymap]]
on   = "l"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on  = "<C-y>"
run = 'shell -- dragon-drop -x -i -T "$1"'

[[mgr.prepend_keymap]]
on   = "P"
run  = "shell -- wl-paste > pasted-image.png"
desc = "Paste image from clipboard"

[[mgr.prepend_keymap]]
on  = "y"
run = [ 'shell -- for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list', "yank" ]

[[mgr.prepend_keymap]]
on = ["<C-o>"]
run = 'shell -- setsid dolphin . '
desc = "Open directory in dolphin"

[[mgr.prepend_keymap]]
on = "d"
run = [ "escape --visual", 'shell -- trash-put "$@"' ]
desc = "Move to trash"

[[mgr.prepend_keymap]]
on   = "!"
run  = 'shell "$SHELL" --block'
desc = "Open $SHELL here"

# trash
[[mgr.prepend_keymap]]
on = ["R", "o"]
run = "plugin recycle-bin -- open"
desc = "Open Trash"
[[mgr.prepend_keymap]]
on = ["R", "e"]
run = "plugin recycle-bin -- empty"
desc = "Empty Trash"
[[mgr.prepend_keymap]]
on = ["R", "D"]
run = "plugin recycle-bin -- emptyDays"
desc = "Empty by days deleted"
[[mgr.prepend_keymap]]
on = ["R", "d"]
run = "plugin recycle-bin -- delete"
desc = "Delete from Trash"
[[mgr.prepend_keymap]]
on = ["R", "r"]
run = "plugin recycle-bin -- restore"
desc = "Restore from Trash"

# compress
[[mgr.prepend_keymap]]
on   = [ "c", "a", "a" ]
run  = "plugin compress"
desc = "Archive selected files"

[[mgr.prepend_keymap]]
on   = [ "c", "a", "p" ]
run  = "plugin compress -p"
desc = "Archive selected files (password)"

[[mgr.prepend_keymap]]
on   = [ "c", "a", "h" ]
run  = "plugin compress -ph"
desc = "Archive selected files (password+header)"

[[mgr.prepend_keymap]]
on   = [ "c", "a", "l" ]
run  = "plugin compress -l"
desc = "Archive selected files (compression level)"

[[mgr.prepend_keymap]]
on   = [ "c", "a", "u" ]
run  = "plugin compress -phl"
desc = "Archive selected files (password+header+level)"

# [[mgr.prepend_keymap]]
# on   = "p"
# run  = "plugin smart-paste"
# desc = "Paste into the hovered directory or CWD"
