[mgr]
prepend_keymap = [
  { on = "l",      run = "plugin smart-enter" },
  { on = "<C-y>",  run = 'shell -- dragon-drop -x -i -T "$1"' },
  { on = "P",      run = "shell -- wl-paste > pasted" },
  { on = "y",      run = [
      'shell -- for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list',
      "yank"
    ] },
  { on = "<C-o>",  run = 'shell -- setsid nemo . ' },
  { on = "d",      run = [ "escape --visual", 'shell -- trash-put "$@"' ] },
  { on = "!",      run = 'shell "$SHELL" --block' },

  { on = ["R","o"], run = "plugin recycle-bin -- open" },
  { on = ["R","e"], run = "plugin recycle-bin -- empty" },
  { on = ["R","D"], run = "plugin recycle-bin -- emptyDays" },
  { on = ["R","d"], run = "plugin recycle-bin -- delete" },
  { on = ["R","r"], run = "plugin recycle-bin -- restore" },

  { on = ["c","a","a"], run = "plugin compress" },
  { on = ["c","a","p"], run = "plugin compress -p" },
  { on = ["c","a","h"], run = "plugin compress -ph" },
  { on = ["c","a","l"], run = "plugin compress -l" },
  { on = ["c","a","u"], run = "plugin compress -phl" },
]

[pick]
prepend_keymap = [
  { on = "<C-n>", run = "arrow next" },
  { on = "<C-p>", run = "arrow prev" },
]
