[flavor]
use = "catppuccin-macchiato"
dark = "catppuccin-macchiato"

[icon]
dirs = [
  { name = "docs", text = "󰲂" },
  { name = "downloads", text = "󰉍" },
  { name = "music", text = "󱍙" },
  { name = "pictures", text = "󰉏" },
  { name = "videos", text = "󰉒" },
  { name = "media", text = "󱧺" },
  { name = "public", text = "󰉌" },
  { name = "tmp", text = "󰪺" },
  { name = "dev", text = "󰲋" },
]
